-- See setup-plugins.lua. Each folder is a tag from NeovimCraft's site
return {
    { import = "kyleking.plugins.bars-and-lines" },
    { import = "kyleking.plugins.buffer" },
    { import = "kyleking.plugins.color" },
    { import = "kyleking.plugins.colorscheme" },
    { import = "kyleking.plugins.completions" },
    { import = "kyleking.plugins.editing-support" },
    { import = "kyleking.plugins.formatting" },
    { import = "kyleking.plugins.fuzzy-finder" },
    { import = "kyleking.plugins.git" },
    { import = "kyleking.plugins.keybinding" },
    { import = "kyleking.plugins.lsp" },
    { import = "kyleking.plugins.marks" },
    { import = "kyleking.plugins.mini" },
    { import = "kyleking.plugins.motion" },
    { import = "kyleking.plugins.programming-languages-support" },
    { import = "kyleking.plugins.search" },
    { import = "kyleking.plugins.session" },
    { import = "kyleking.plugins.split-and-window" },
    { import = "kyleking.plugins.syntax" },
    { import = "kyleking.plugins.terminal-integration" },
    { import = "kyleking.plugins.utility" },
}
